services:
  cf-ddns:
    build: .
    env_file:
      - .env
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    networks:
      - cf-ddns

networks:
  cf-ddns:
